import "../styles/globals.css"
import { Inter } from "next/font/google"
import Header from "@/components/header"
import { getAllRootCategories } from "@/lib/contentful"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: {
        template: "%s | Next.js app",
        default: "Next.js app",
    },
    description: "Generated by Next.js",
}

export default async function RootLayout({ children }) {
    const categories = await getAllRootCategories()
    return (
        <html lang="en">
            <body className={inter.className}>
                <div className="mx-auto w-[90%] lg:w-[50rem] xl:w-[75rem]">
                    <Header categories={categories} className="mt-2 mb-5" />
                    {children}
                    <div className="mt-6"></div>
                </div>
            </body>
        </html>
    )
}
