import '../styles/globals.css'
import { Inter } from 'next/font/google'
import { cn } from "@/lib/utils"
import Header from '@/components/header'
import { getAllRootCategories } from "@/lib/contentful"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: {
        template: "%s | Next.js app",
        default: "Next.js app",
    },
    description: "Generated by Next.js",
}

export default async function RootLayout({ children }) {
    const categories = await getAllRootCategories()
    return (
        <html lang="en">
            <body className={cn(
                                inter.className,
                                "mx-auto w-[90%] lg:w-[50rem] xl:w-[75rem]"
                            )}>
                <Header categories={categories} />
                {children}
            </body>
        </html>
    )
}
